global using Bogus;
global using Castle.Windsor;
global using FluentAssertions;
global using Framework;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Moq;
global using Tests.Shared;
global using Xunit;